set(SDL_IMAGE_INCLUDE_DIRS "${CMAKE_CURRENT_LIST_DIR}/include")

if (CMAKE_SIZEOF_VOID_P EQUAL 8)
	set(SDL_IMAGE_LIBRARIES "${CMAKE_CURRENT_LIST_DIR}/lib/x64/SDL2_image.lib;")
	set(SDL_IMAGE_BINARIES "${CMAKE_CURRENT_LIST_DIR}/lib/x64/SDL2_image.dll")
else()
	set(SDL_IMAGE_LIBRARIES "${CMAKE_CURRENT_LIST_DIR}/lib/x86/SDL2_image.lib;")
	set(SDL_IMAGE_BINARIES "${CMAKE_CURRENT_LIST_DIR}/lib/x86/SDL2_image.dll")
endif()

string(STRIP "${SDL2_IMAGE_LIBRARIES}" SDL2_IMAGE_LIBRARIES)