MESH_SIDE = 16
MESH_STIFFNESS = .7
ATTRACTION_CONSTANT = 6.67 * 10
TIME_DERIVATIVE = .1
WATER_ATTRACTION = .7

"""
Water & lava map parameters
"""
MAX_WATER_EXPLORATION = 100
MAX_LAVA_EXPLORATION = 50
MIN_DIST_TO_LAVA = 10
MIN_DIST_TO_OCEAN = 8
MIN_DIST_TO_RIVER = 4
